import { Button, VerticalBox, LineEdit, HorizontalBox, GroupBox, ComboBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <string> g_reading;
    in-out property <string> unit_type: "mg/dL";
    in-out property <string> k_reading;
    in property <string> gki_result;
    callback calculate_gki();
    
    VerticalBox {
        padding: 20px;
        Text {
            font-size: 24px;
            horizontal-alignment: center;
            text: "GKI Calculator";
        }
        GroupBox {
            title: "Glucose Reading:";
            HorizontalLayout {
                spacing: 10px;
                LineEdit {
                    width: 200px;
                    placeholder-text: "83.0";
                    edited => {
                        root.g_reading = self.text
                    }
                }
                ComboBox {
                    model: ["mg/dL", "mmol/L"];
                    current-value: "mg/dL";
                    width: 100px;
                    selected => {
                        root.unit_type = self.current-value
                    }
                }
            }
        }
        
        
        GroupBox {
            title: "Ketone Reading:";
            HorizontalLayout {
                spacing: 10px;
                LineEdit {
                    width: 200px;
                    placeholder-text: "1.8";
                    edited => {
                        root.k_reading = self.text
                    }
                }
                Text {
                    vertical-alignment: center;
                    text: "mmol/L";
                }
            }
        }

        GroupBox {
            
            HorizontalLayout {
                spacing: 10px;
                Button {
                    width: 200px;
                    height: 60px;
                    text: "Calculate GKI";
                    primary: true;
                    clicked =>  {
                        root.calculate_gki()
                    }
                }
                Text {
                    vertical-alignment: center;
                    horizontal-alignment: center;
                    font-size: 24px;
                    text: root.gki_result;
                }
            }
        }
        
        
    }
}
